function drawBox3D(h_axes,object,corners,face_idx,orientation)
  
  % draw projected 3D bounding boxes
  if ~isempty(corners)
    for f=1:4
      line([corners(1,face_idx(f,:)),corners(1,face_idx(f,1))]+1,...
           [corners(2,face_idx(f,:)),corners(2,face_idx(f,1))]+1,...
           'parent',h_axes,...
           'LineWidth',3);
      line([corners(1,face_idx(f,:)),corners(1,face_idx(f,1))]+1,...
           [corners(2,face_idx(f,:)),corners(2,face_idx(f,1))]+1,...
           'parent',h_axes,'color','b','LineWidth',1);
    end
  end
  
  % draw orientation vector
  if ~isempty(orientation)
    line([orientation(1,1),orientation(1,2)]+1,...
         [orientation(2,1),orientation(2,2)]+1,...
         'parent',h_axes,'color','w','LineWidth',4);
    line([orientation(1,2),orientation(1,3)]+1,...
         [orientation(2,2),orientation(2,3)]+1,...
         'parent',h_axes,'color','w','LineWidth',4);
    line([orientation(1,2),orientation(1,4)]+1,...
         [orientation(2,2),orientation(2,4)]+1,...
         'parent',h_axes,'color','w','LineWidth',4);
        
    line([orientation(1,1),orientation(1,2)]+1,...
         [orientation(2,1),orientation(2,2)]+1,...
         'parent',h_axes,'color','k','LineWidth',2);
    line([orientation(1,2),orientation(1,3)]+1,...
         [orientation(2,2),orientation(2,3)]+1,...
         'parent',h_axes,'color','k','LineWidth',2);
    line([orientation(1,2),orientation(1,4)]+1,...
         [orientation(2,2),orientation(2,4)]+1,...
         'parent',h_axes,'color','k','LineWidth',2);
  end
end
